accounts/urls.py
from django.conf.urls import url
from accounts import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^register/personal', views.register_personal, name='register_personal'),
    url(r'^update/personal/(?P<user_id>[0-9]+)/$', views.update_personal, name='update_personal'),
    url(r'^delete/personal/(?P<user_id>[0-9]+)/$', views.delete_personal, name='delete_personal'),
    url(r'^personal/(?P<user_id>[0-9]+)/$', views.detail_personal, name='detail_personal'),

    url(r'^update/profile/$', views.update_profile, name='update_profile'),
    url(r'^profile/$', views.show_profile, name='show_profile'),

    url(r'^users/$', views.user_list, name='user_list')

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

docapp/urls.py
from django.conf.urls import url
from docapp import views

urlpatterns = [
    url(r'^dashboard/$', views.dashboard, name='dashboard'),
    # Company urls
    url(r'^company/$', views.list_company, name='list_company'),
    url(r'^company/(?P<company_id>[0-9]+)/$', views.detail_company, name='detail_company'),
    url(r'^register/company/$', views.register_company, name='register_company'),
    url(r'^update/company/(?P<company_id>[0-9]+)/$', views.update_company, name='update_company'),
    url(r'^employs/company/(?P<company_id>[0-9])+/$', views.list_employ_company, name='list_employ_company'),

    # Employ urls
    url(r'^person/$', views.list_independent_employ, name='list_independent_employ'),
    url(r'^person/(?P<person_id>[0-9]+)/$', views.detail_employ, name='detail_employ'),
    url(r'^register/person/$', views.register_employ_without_company, name='register_employ_without_company'),
    url(r'^register/person/(?P<company_id>[0-9]+)/$', views.register_employ_from_company,
        name='register_employ_from_company'),
    url(r'^update/person/(?P<person_id>[0-9]+)/$', views.update_employ, name='update_employ'),

    # Particular urls
    url(r'^patient/$', views.list_simple_patient, name='list_simple_patient'),
    url(r'^patient/(?P<pk>[0-9]+)/$', views.detail_patient, name='detail_patient'),
    url(r'^register/patient/$', views.register_simple_patient, name='register_simple_patient'),
    url(r'^update/patient/(?P<pk>[0-9]+)/$', views.update_simple_patient, name='update_simple_patient'),

    # Consults urls
    url(r'^consult/$', views.make_consulta, name='make_consult'),
    url(r'^assign_consult/$', views.assign_consult, name='assign_consult'),
    url(r'^enable_consults/$', views.list_consults_enable, name='enable_consults'),
    url(r'^consults/$', views.list_consults, name='list_consults'),
    url(r'^own_consults/$', views.lab_own_consults, name='list_own_consults'),
    url(r'^end_consult/$', views.end_consult, name='end_consult'),
    url(r'^list_end_consult/$', views.list_end_consults, name='list_end_consults'),


    # Antecedent urls
    url(r'^antecedent/(?P<person_id>[0-9])/$', views.list_employ_antecedents, name='list_employ_antecedents'),
    url(r'^antecedent/detail/(?P<antecedent_id>[0-9]+)/$', views.detail_employ_antecedent,
        name='detail_employ_antecedent'),
    url(r'^register/antecedent/(?P<person_id>[0-9]+)/$', views.register_employ_antecedent,
        name='register_employ_antecedent'),
    url(r'^update/antecedent/(?P<antecedent_id>[0-9]+)/$', views.update_employ_antecedent,
        name='update_employ_antecedent'),

    # Examination urls
    url(r'^register/exam/(?P<person_id>[0-9]+)/$', views.register_employ_examination,
        name='register_employ_examination'),
    url(r'^examination/$', views.list_examination, name='list_examination'),
    url(r'^examination/(?P<exam_id>[0-9]+)/$', views.detail_examination, name='detail_examination'),
    url(r'^take/examination/(?P<exam_id>[0-9]+)/$', views.take_a_exam, name='doctor_take_a_exam'),
    url(r'^my/examinations/$', views.own_examinations, name='doctor_own_examinations'),
    url(r'^end/examination/(?P<exam_id>[0-9]+)/$', views.doctor_end_exam, name='doctor_end_exam'),
    url(r'^end/examinations/$', views.end_examinations, name='doctor_end_examinations'),


    # Registro de examanes
    url(r'^register/(?P<exam_id>[0-9]+)/occupational/$', views.register_occupational, name='register_occupational'),
    url(r'^register/(?P<exam_id>[0-9]+)/audiology/$', views.register_audiology, name='register_audiology'),
    url(r'^register/(?P<exam_id>[0-9]+)/visiometry/$', views.register_visiometry, name='register_visiometry'),
    url(r'^register/(?P<exam_id>[0-9]+)/altura/$', views.register_altura, name='register_altura'),

    # Update exams
    url(r'^occupational/(?P<pk>[0-9]+)/$', views.update_ocupacional, name='update_ocupacional'),
    url(r'^audiology/(?P<pk>[0-9]+)/$', views.update_audiologia, name='update_audiologia'),
    url(r'^visiometry/(?P<pk>[0-9]+)/$', views.update_visiometria, name='update_visiometria'),
    url(r'^altura/(?P<pk>[0-9]+)/$', views.update_altura, name='update_altura'),
    url(r'^simple_exam/(?P<pk>[0-9]+)/$', views.register_simple_exam, name='register_simple_exam'),

    # Lab urls
    url(r'^labs/$', views.list_lab, name='list_lab'),
    url(r'^lab/(?P<pk>[0-9]+)/admin/$', views.list_admin_lab, name='list_admin_lab'),
    url(r'^register/lab/$', views.register_lab, name='register_lab'),
    url(r'^update/lab/(?P<lab_id>[0-9])/$', views.update_lab, name='update_lab'),
    url(r'^deactivate/lab/(?P<lab_id>[0-9])/$', views.deactivate_lab, name='deactivate_lab'),
    url(r'^register/lab/(?P<lab_id>[0-9]+)/admin/$', views.register_lab_admin, name='register_lab_admin'),
    url(r'^update/lab/admin/(?P<pk>[0-9]+)/$', views.update_lab_admin, name='update_lab_admin'),
    url(r'^delete/lab/admin/(?P<pk>[0-9]+)/$', views.deactivate_lab_admin, name='deactivate_lab_admin'),
    url(r'^lab/admin/(?P<pk>[0-9]+)/$', views.detail_lab_admin, name='detail_lab_admin'),
    url('^laboratory/(?P<lab_id>[0-9]+)/$', views.detail_laboratory, name='detail_laboratory'),

    # Other
    url('^filter/$', views.person_filter, name='person_filter')
]

docproject/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url('^grappelli/', include('grappelli.urls')),  # grappelli URLS
    url(r'^admin/', admin.site.urls),
    url(r'', include('docapp.urls', namespace='docapp')),
    url(r'', include('accounts.urls', namespace='accounts')),
    url(r'^labapp/', include('labapp.urls', namespace='labapp')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

labapp/urls.py
from django.conf.urls import url
from labapp import views

urlpatterns = [
    url('^register/personal/$', views.register_personal, name='register_personal'),
    url('^list/examinations/$', views.list_examination_todo, name='list_examination_todo'),
    url('^my/examinations/$', views.lab_own_examinations, name='lab_own_examinations'),
    url('^take/examination/(?P<exam_id>[0-9]+)/$', views.lab_take_a_exam, name='lab_take_a_exam'),
    url('^register/result/(?P<pk>[0-9]+)/$', views.register_lab_exam_result, name='register_lab_exam_result'),
    url('^update/results/(?P<pk>[0-9]+)/$', views.update_lab_exam_result, name='update_lab_exam_result'),
    url('^end/examination/(?P<exam_id>[0-9]+)/$', views.lab_end_exam, name='lab_end_exam'),
    url('^end/examinations/$', views.lab_end_examinations, name='lab_end_examinations')
]

docapp/views/doctor.py
from django import forms
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db import IntegrityError
from django.db.models import Count, Q, F
from django.http import HttpResponseRedirect
from django.shortcuts import redirect
from django.views.decorators.http import require_POST
from django.views.generic import UpdateView, DetailView, TemplateView, ListView
from django.core.exceptions import ObjectDoesNotExist, SuspiciousOperation
from django.core.urlresolvers import reverse_lazy
from django.contrib import messages
from django.views.generic.detail import SingleObjectMixin

from docapp.models import (PacienteEmpresa, Occupational, Audiology, Visiometry, Altura, AntecedentesLaborales, Riesgos,
                           Accidentes, SimpleExam, Examinacion, Consulta)
from docapp.forms import (OcupaForm,
                          ant_familiares_section,
                          ant_gineco_section,
                          revision_sistemas_section,
                          biometria_section,
                          habito_alcohol_section, habito_cigarillo_section, habito_droga_section,
                          habito_general_section,
                          examen_fisico_general_section, examen_fisico_abdomen_section, examen_fisico_boca_section,
                          examen_fisico_columna_section, examen_fisico_corazon_section, examen_fisico_cuello_section,
                          examen_fisico_extremidades_section, examen_fisico_genito_unitario_section,
                          examen_fisico_nariz_section, examen_fisico_neurologico_section, examen_fisico_oidos_section,
                          examen_fisico_ojos_section, examen_fisico_torax_pulmones_section,
                          conclusion_ingreso_section,
                          conclusion_periodico_section,
                          conclusion_post_incapacidad_section,
                          conclusion_retiro_section)

from docapp.forms import (AudioForm,
                          ananmesis_section,
                          ant_familiar_section,
                          ant_otro_section,
                          exposicion_audifonos_section, exposicion_moto_section, exposicion_auto_section,
                          exposicion_pesada_section,
                          estado_actual_ruido_molestia_section, estado_actual_volumen_tv_section,
                          estado_actual_frases_repetidas_section, estado_actual_escucha_section,
                          estado_actual_escucha_ruido_section,
                          audiometria_section)

from docapp.forms import (VisioForm, sintomas_section, ant_enfermedad_section, ant_uso_lentes_section,
                          ant_extra_exams, agudeza_section, cronomatica_section,
                          AntLaboralesForm, hazards_inlineformset, accident_inlineformset)

from docapp.forms import AlturaForm, question_section, SimpleExamForm

from docproject.helpers.chekers import CheckDoctor, CheckLaboratory, CheckUser
from docproject.helpers.customs import (FormViewPutExtra, FormsetPostManager, BaseRegisterExamBehavior,
                                        BaseExamUpdateBehavior)
from docapp.choices import ExamStates
from django.shortcuts import get_object_or_404

from accounts.models import DoctorProfile, ReceptionProfile


class RegisterOccupational(LoginRequiredMixin, CheckDoctor, BaseRegisterExamBehavior, FormsetPostManager,
                           FormViewPutExtra):
    model = Occupational
    form_class = OcupaForm
    template_name = 'docapp/register/exams/occupational.html'
    extra_context = {'exam_name': 'ocupacional',
                     'parent_object_key': 'ocupacional_id',
                     'child_name': 'ocupacional',
                     'formsets': [
                         {'section_name': 'ant_familiares',
                          'title': 'Antecedentes Familiares',
                          'form': ant_familiares_section},
                         None,
                         {'section_name': 'revision_sistemas',
                          'title': 'Revision por Sistemas',
                          'form': revision_sistemas_section},
                         # Habitos
                         {'section_name': 'habitos_generales',
                          'title': 'Habitos Generales',
                          'form': habito_general_section},
                         {'section_name': 'habito_alcohol',
                          'title': 'Habito Alcohol',
                          'form': habito_alcohol_section},
                         {'section_name': 'habito_cigarrillo',
                          'title': 'Habito Cigarillo',
                          'form': habito_cigarillo_section},
                         {'section_name': 'habito_droga',
                          'title': 'Habito Droga',
                          'form': habito_droga_section},
                         # Examen Fisico
                         {'section_name': 'aspecto_general',
                          'title': 'Aspecto General',
                          'form': examen_fisico_general_section},
                         {'section_name': 'biometria',
                          'title': 'Biometria',
                          'form': biometria_section},
                         # # Organos de los sentidos
                         {'section_name': 'org_boca',
                          'title': 'Boca',
                          'form': examen_fisico_boca_section},
                         {'section_name': 'org_nariz',
                          'title': 'Nariz',
                          'form': examen_fisico_nariz_section},
                         {'section_name': 'org_oidos',
                          'title': 'Oidos',
                          'form': examen_fisico_oidos_section},
                         {'section_name': 'org_ojos',
                          'title': 'Ojos',
                          'form': examen_fisico_ojos_section},
                         # # Fin Organos
                         {'section_name': 'exm_cuello',
                          'title': 'Cuello',
                          'form': examen_fisico_cuello_section},
                         {'section_name': 'exm_torax_pulmones',
                          'title': 'Torax y Pulmones',
                          'form': examen_fisico_torax_pulmones_section},
                         {'section_name': 'exm_corazon',
                          'title': 'Corazon',
                          'form': examen_fisico_corazon_section},
                         {'section_name': 'exm_abdomen',
                          'title': 'Abdomen',
                          'form': examen_fisico_abdomen_section},
                         {'section_name': 'exm_columna',
                          'title': 'Columna',
                          'form': examen_fisico_columna_section},
                         {'section_name': 'exm_extremidades',
                          'title': 'Extremidades',
                          'form': examen_fisico_extremidades_section},
                         {'section_name': 'exm_neurologico',
                          'title': 'Neurologico',
                          'form': examen_fisico_neurologico_section},
                         {'section_name': 'exm_genito_unitario',
                          'title': 'Genito Unitario',
                          'form': examen_fisico_genito_unitario_section},
                         # Fin examen fisico
                         None
                     ]
                     }

    def get_context_data(self, **kwargs):
        examination = self.get_object()
        examination_patient = examination.paciente_id
        if examination_patient.sexo == 'femenino' and self.extra_context['formsets'][1] is None:
            self.extra_context['formsets'][1] = {'section_name': 'ant_gineco',
                                                 'title': 'Antecedentes Gineco-Obstricos',
                                                 'form': ant_gineco_section}
        if self.extra_context['formsets'][21] is None:
            conclusion_section = {'section_name': 'conclusion',
                                  'title': 'Conclusion',
                                  'form': None}
            if examination.tipo == 'ingreso':
                conclusion_section.update({'form': conclusion_ingreso_section})
            elif examination.tipo == 'periodico':
                conclusion_section.update({'form': conclusion_periodico_section})
            elif examination.tipo == 'retiro' or examination.tipo == 'reubicacion':
                conclusion_section.update({'form': conclusion_retiro_section})
            elif examination.tipo == 'post-incapacidad':
                conclusion_section.update({'form': conclusion_post_incapacidad_section})
            else:
                raise SuspiciousOperation("Contact Admin")

            self.extra_context['formsets'][21] = conclusion_section
        return super(RegisterOccupational, self).get_context_data(**kwargs)


register_occupational = RegisterOccupational.as_view()


class UpdateOccupational(LoginRequiredMixin, CheckDoctor, BaseExamUpdateBehavior, FormsetPostManager, UpdateView):
    model = Occupational
    form_class = OcupaForm
    template_name = 'docapp/register/exams/occupational.html'
    extra_context = {'exam_name': 'ocupacional',
                     'parent_object_key': 'ocupacional_id',
                     'formsets': [
                         {'section_name': 'ant_familiares',
                          'title': 'Antecedentes Familiares',
                          'form': ant_familiares_section},
                         None,
                         {'section_name': 'revision_sistemas',
                          'title': 'Revision por Sistemas',
                          'form': revision_sistemas_section},

templates/docapp/lists/exam_list.html
{% extends 'base/base_list.html' %}

{% block title %} Procesos | Examinaciones {% endblock %}


{% block page_title %}Lista de Examinaciones {% endblock %}
{% block small_message %} Lista de examinaciones en proceso {% endblock %}
{% block add_btn %} {% endblock %}

{% block datatable_body %}
    <thead>
    <tr>
        <th>ID</th>
        <th>Tipo de examen</th>
        <th>Paciente</th>
        <th>Creador</th>
        <th>Fecha de Creación</th>
        <th>Estado</th>
        <th>Acciones</th>
    </tr>
    </thead>
    <tbody>
    {% for exam in exam_list %}
        <tr>
            <td>{{ exam.id }}</td>
            <td> {{ exam.tipo }} </td>
            <td> {{ exam.paciente_id }}
                <br>
                {% if request.user.doctor_profile %}
                    <button class="btn btn-primary btn-xs btn_modal" data-toggle="tooltip"
                            data-placement="left" data-modal-title="Detalle Empleado" data-original-title="Ver"
                            href="{% url 'docapp:detail_employ' person_id=exam.paciente_id_id %}">
                        <i class="fa fa-eye" aria-hidden="true"></i>
                    </button>
                    <a href="{% url 'docapp:register_employ_antecedent' person_id=exam.paciente_id_id %}">
                        <button class="btn btn-warning btn-xs" data-toggle="tooltip"
                                data-placement="left" title="" data-original-title="Registrar Antecedentes">
                            <i class="fa fa-edit" aria-hidden="true"></i>
                        </button>
                    </a>
                {% endif %}
            </td>
            <td> {{ exam.registrado_por.user_id }}
                <br>
                {% if request.user.is_superuser %}
                    <button class="btn btn-primary btn-xs btn_modal" data-toggle="tooltip"
                            data-placement="left" data-modal-title="Detalle Usuario" data-original-title="Ver"
                            href="{% url 'accounts:detail_personal' user_id=exam.registrado_por.user_id_id %}">
                        <i class="fa fa-eye" aria-hidden="true"></i>
                    </button>
                {% endif %}
            </td>
            <td> {{ exam.fecha_de_creacion }} </td>
            <td>
                {% if request.user.doctor_profile %}
                    {{ exam.doctor_estado }}
                    {% if exam.get_doctor_process == 100 and request.path == '/my/examinations/' %}
                        <button class="btn btn-primary btn-xs btn_modal" data-modal-title="Terminar Examinacion"
                                href="{% url 'docapp:doctor_end_exam' exam_id=exam.id %}">
                            <i class="fa fa-send" aria-hidden="true"></i>
                        </button>
                    {% endif %}
                {% elif request.user.laboratory_profile %}
                    {{ exam.lab_estado }}
                    {% if exam.get_lab_process == 100 and request.path == '/labapp/my/examinations/' %}
                        <button class="btn btn-primary btn-xs btn_modal" data-modal-title="Terminar Examinacion"
                                href="{% url 'labapp:lab_end_exam' exam_id=exam.id %}">
                            <i class="fa fa-send" aria-hidden="true"></i>
                        </button>
                    {% endif %}
                {% else %}
                    {{ exam.estado }}
                {% endif %}
            </td>
            {% if request.user.is_authenticated %}
                <td>
                    {% if request.user.doctor_profile %}
                        {% if request.path == '/examination/' %}
                            <button type="button" class="btn btn-success btn_modal"
                                    href="{% url 'docapp:doctor_take_a_exam' exam_id=exam.id %}">
                                Tomar Examinacion
                            </button>
                        {% elif request.path == '/my/examinations/' %}
                            <button type="button" class="btn btn-success btn_modal"
                                    href="{% url 'docapp:detail_examination' exam_id=exam.id %}">
                                Registar Resultados
                            </button>
                        {% endif %}
                    {% elif request.user.laboratory_profile %}
                        {% if request.path == '/labapp/list/examinations/' %}
                            <button type="button" class="btn btn-success btn_modal"
                                    href="{% url 'labapp:lab_take_a_exam' exam_id=exam.id %}">
                                Tomar Examinacion
                            </button>
                        {% elif request.path == '/labapp/my/examinations/' %}
                            <button type="button" class="btn btn-success btn_modal"
                                    href="{% url 'docapp:detail_examination' exam_id=exam.id %}">
                                Registar Resultados
                            </button>
                        {% endif %}
                    {% elif request.user.reception_profile %}
                        <button type="button" class="btn btn-success btn_modal" data-modal-title="Resumen"
                                href="{% url 'docapp:detail_examination' exam_id=exam.id %}">
                            Detalles
                        </button>
                    {% endif %}
                </td>
            {% endif %}
        </tr>

    {% endfor %}
    </tbody>
{% endblock %}
{% block extra_content %}
    {% include 'base/base_modal.html' %}
{% endblock %}
{% block scripts %}
    {{ block.super }}
    <script>
        $('.btn_modal').on('click', function (event) {
            event.preventDefault();
            load_modal(this.dataset.modalTitle, "success", this.getAttribute('href'));
        });
    </script>
{% endblock %}

templates/docapp/lists/person_list.html
{% extends 'base/base_list.html' %}
{% load static %}
{% block title %} Lista Personas {% endblock %}

{% block page_title %}Personas Independientes{% endblock %}
{% block small_message %} Lista de personas independientes {% endblock %}
{% block add_link %} {% url 'docapp:register_employ_without_company' %} {% endblock %}
{% block add_link_label %} Persona {% endblock %}

{% block datatable_body %}
    <thead>
    <tr>
        <th>Identificacion</th>
        <th>Nombre</th>
        <th>Apellido</th>
        <th>Telefono</th>
        <th>Celular</th>
        <th>Sexo</th>
        <th>Empresa</th>
        <th>Examinacion</th>
        {% if request.user.doctor_profile %}<th>Antecedentes</th>{% endif %}
        <th>Opciones</th>
    </tr>
    </thead>
    <tbody>
    {% for person in person_list %}
        <tr>
            <td>{{ person.identificacion }}</td>
            <td>{{ person.nombres }}</td>
            <td>{{ person.apellidos }}</td>
            <td>{{ person.telefono }}</td>
            <td>{{ person.celular }}</td>
            <td>{{ person.sexo }}</td>
            <td>{% if person.empresa %} {{ person.empresa }} {% else %} No
                presenta {% endif %}</td>
            <td>
                <a href="{% url 'docapp:register_employ_examination' person_id=person.id %}">
                    <button class="btn btn-warning btn-xs" data-toggle="tooltip"
                            data-placement="left" title="" data-original-title="Iniciar">
                        Registro <i class="fa fa-pencil" aria-hidden="true"></i>
                    </button>
                </a>
            </td>
            {% if request.user.doctor_profile %}
                <td>
                    <!-- Register Link -->
                    <a href="{% url 'docapp:register_employ_antecedent' person_id=person.id %}">
                        <button class="btn btn-warning btn-xs" data-toggle="tooltip"
                                data-placement="left" title="" data-original-title="Registrar">
                            Registro <i class="fa fa-pencil" aria-hidden="true"></i>
                        </button>
                    </a>
                    <!-- List Link -->
                    <a href="{% url 'docapp:list_employ_antecedents' person_id=person.id %}">
                        <button class="btn btn-primary btn-xs" data-toggle="tooltip"
                                data-placement="left" title="" data-original-title="Ver lista">
                            <i class="fa fa-list-alt" aria-hidden="true"></i> Lista
                        </button>
                    </a>
                </td>
            {% endif %}
            <td>
                <!-- Detail Link -->
                <button class="btn btn-primary btn-xs btn_modal" data-toggle="tooltip"
                        data-placement="left" data-modal-title="Detalle Empleado" data-original-title="Ver"
                        href="{% url 'docapp:detail_employ' person_id=person.id %}">
                    Ver <i class="fa fa-eye" aria-hidden="true"></i>
                </button>
                <!-- Update Link -->
                <a href="{% url 'docapp:update_employ' person_id=person.id %}">
                    <button class="btn btn-warning btn-xs" data-toggle="tooltip"
                            data-placement="left" title="" data-original-title="Editar">
                        <i class="fa fa-edit" aria-hidden="true"></i> Editar
                    </button>
                </a>
            </td>
        </tr>
    {% endfor %}
    </tbody>
{% endblock %}
{% block extra_content %}
    {% include 'base/base_modal.html' %}
{% endblock %}
{% block extra_scripts %}
    <script>
        $('.btn_modal').on('click', function (event) {
            event.preventDefault();
            load_modal(this.dataset.modalTitle, "success", this.getAttribute('href'));
        });
    </script>
{% endblock %}

templates/docapp/lists/person_list_company.html
{% extends 'base/base_list.html' %}
{% load static %}
{% block title %} Lista Empleados {% endblock %}

{% block page_title %}Empleados Registrados de {{ company }}{% endblock %}
{% block small_message %} Lista de empleados {% endblock %}
{% block add_link %} {% url 'docapp:register_employ_from_company' company_id=company.id %} {% endblock %}
{% block add_link_label %} Empleado {% endblock %}

{% block datatable_body %}
    <thead>
    <tr>
        <th>Identificacion</th>
        <th>Nombre</th>
        <th>Apellido</th>
        <th>Telefono</th>
        <th>Celular</th>
        <th>Sexo</th>
        <th>Examinacion</th>
        {% if request.user.doctor_profile %}
            <th>Antecedentes</th>{% endif %}
        <th>Opciones</th>
    </tr>
    </thead>
    <tbody>
    {% for person in company.empleados.all %}
        <tr>
            <td>{{ person.identificacion }}</td>
            <td>{{ person.nombres }}</td>
            <td>{{ person.apellidos }}</td>
            <td>{{ person.telefono }}</td>
            <td>{{ person.celular }}</td>
            <td>{{ person.sexo }}</td>
            <td>
                <a href="{% url 'docapp:register_employ_examination' person_id=person.id %}">
                    <button class="btn btn-warning btn-xs">
                        Registro <i class="fa fa-pencil" aria-hidden="true"></i>
                    </button>
                </a>
            </td>
            {% if request.user.doctor_profile %}
                <td>
                    <!-- Register Link -->
                    <a href="{% url 'docapp:register_employ_antecedent' person_id=person.id %}">
                        <button class="btn btn-warning btn-xs" data-toggle="tooltip"
                                data-placement="left" title="" data-original-title="Registrar">
                            <i class="fa fa-pencil" aria-hidden="true"></i>
                        </button>
                    </a>
                    <!-- List Link -->
                    <a href="{% url 'docapp:list_employ_antecedents' person_id=person.id %}">
                        <button class="btn btn-primary btn-xs" data-original-title="Ver lista">
                            <i class="fa fa-list-alt" aria-hidden="true"></i> Lista
                        </button>
                    </a>
                </td>{% endif %}
            <td>
                <!-- Detail Link -->
                <button class="btn btn-primary btn-xs btn_modal" data-modal-title="Detalle Empleado"
                        href="{% url 'docapp:detail_employ' person_id=person.id %}">
                    Ver <i class="fa fa-eye" aria-hidden="true"></i>
                </button>
                <!-- Update Link -->
                <a href="{% url 'docapp:update_employ' person_id=person.id %}">
                    <button class="btn btn-warning btn-xs">
                        <i class="fa fa-edit" aria-hidden="true"></i> Editar
                    </button>
                </a>
            </td>
        </tr>
    {% endfor %}
    </tbody>
{% endblock %}
{% block extra_content %}
    {% include 'base/base_modal.html' %}
{% endblock %}
{% block extra_scripts %}
    <script>
        $('.btn_modal').on('click', function (event) {
            event.preventDefault();
            load_modal(this.dataset.modalTitle, "success", this.getAttribute('href'));
        });
    </script>
{% endblock %}