accounts/urls.py
from django.conf.urls import url
from accounts import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^register/personal', views.register_personal, name='register_personal'),
    url(r'^update/personal/(?P<user_id>[0-9]+)/$', views.update_personal, name='update_personal'),
    url(r'^delete/personal/(?P<user_id>[0-9]+)/$', views.delete_personal, name='delete_personal'),
    url(r'^personal/(?P<user_id>[0-9]+)/$', views.detail_personal, name='detail_personal'),

    url(r'^update/profile/$', views.update_profile, name='update_profile'),
    url(r'^profile/$', views.show_profile, name='show_profile'),

    url(r'^users/$', views.user_list, name='user_list')

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

docapp/urls.py
from django.conf.urls import url
from docapp import views

urlpatterns = [
    url(r'^dashboard/$', views.dashboard, name='dashboard'),
    # Company urls
    url(r'^company/$', views.list_company, name='list_company'),
    url(r'^company/(?P<company_id>[0-9]+)/$', views.detail_company, name='detail_company'),
    url(r'^register/company/$', views.register_company, name='register_company'),
    url(r'^update/company/(?P<company_id>[0-9]+)/$', views.update_company, name='update_company'),
    url(r'^employs/company/(?P<company_id>[0-9])+/$', views.list_employ_company, name='list_employ_company'),

    # Employ urls
    url(r'^person/$', views.list_independent_employ, name='list_independent_employ'),
    url(r'^person/(?P<person_id>[0-9]+)/$', views.detail_employ, name='detail_employ'),
    url(r'^register/person/$', views.register_employ_without_company, name='register_employ_without_company'),
    url(r'^register/person/(?P<company_id>[0-9]+)/$', views.register_employ_from_company,
        name='register_employ_from_company'),
    url(r'^update/person/(?P<person_id>[0-9]+)/$', views.update_employ, name='update_employ'),

    # Particular urls
    url(r'^patient/$', views.list_simple_patient, name='list_simple_patient'),
    url(r'^patient/(?P<pk>[0-9]+)/$', views.detail_patient, name='detail_patient'),
    url(r'^register/patient/$', views.register_simple_patient, name='register_simple_patient'),
    url(r'^update/patient/(?P<pk>[0-9]+)/$', views.update_simple_patient, name='update_simple_patient'),

    # Consults urls
    url(r'^consult/$', views.make_consulta, name='make_consult'),
    url(r'^assign_consult/$', views.assign_consult, name='assign_consult'),
    url(r'^enable_consults/$', views.list_consults_enable, name='enable_consults'),
    url(r'^consults/$', views.list_consults, name='list_consults'),
    url(r'^own_consults/$', views.lab_own_consults, name='list_own_consults'),
    url(r'^end_consult/$', views.end_consult, name='end_consult'),
    url(r'^list_end_consult/$', views.list_end_consults, name='list_end_consults'),


    # Antecedent urls
    url(r'^antecedent/(?P<person_id>[0-9])/$', views.list_employ_antecedents, name='list_employ_antecedents'),
    url(r'^antecedent/detail/(?P<antecedent_id>[0-9]+)/$', views.detail_employ_antecedent,
        name='detail_employ_antecedent'),
    url(r'^register/antecedent/(?P<person_id>[0-9]+)/$', views.register_employ_antecedent,
        name='register_employ_antecedent'),
    url(r'^update/antecedent/(?P<antecedent_id>[0-9]+)/$', views.update_employ_antecedent,
        name='update_employ_antecedent'),

    # Examination urls
    url(r'^register/exam/(?P<person_id>[0-9]+)/$', views.register_employ_examination,
        name='register_employ_examination'),
    url(r'^examination/$', views.list_examination, name='list_examination'),
    url(r'^examination/(?P<exam_id>[0-9]+)/$', views.detail_examination, name='detail_examination'),
    url(r'^take/examination/(?P<exam_id>[0-9]+)/$', views.take_a_exam, name='doctor_take_a_exam'),
    url(r'^my/examinations/$', views.own_examinations, name='doctor_own_examinations'),
    url(r'^end/examination/(?P<exam_id>[0-9]+)/$', views.doctor_end_exam, name='doctor_end_exam'),
    url(r'^end/examinations/$', views.end_examinations, name='doctor_end_examinations'),


    # Registro de examanes
    url(r'^register/(?P<exam_id>[0-9]+)/occupational/$', views.register_occupational, name='register_occupational'),
    url(r'^register/(?P<exam_id>[0-9]+)/audiology/$', views.register_audiology, name='register_audiology'),
    url(r'^register/(?P<exam_id>[0-9]+)/visiometry/$', views.register_visiometry, name='register_visiometry'),
    url(r'^register/(?P<exam_id>[0-9]+)/altura/$', views.register_altura, name='register_altura'),

    # Update exams
    url(r'^occupational/(?P<pk>[0-9]+)/$', views.update_ocupacional, name='update_ocupacional'),
    url(r'^audiology/(?P<pk>[0-9]+)/$', views.update_audiologia, name='update_audiologia'),
    url(r'^visiometry/(?P<pk>[0-9]+)/$', views.update_visiometria, name='update_visiometria'),
    url(r'^altura/(?P<pk>[0-9]+)/$', views.update_altura, name='update_altura'),
    url(r'^simple_exam/(?P<pk>[0-9]+)/$', views.register_simple_exam, name='register_simple_exam'),

    # Lab urls
    url(r'^labs/$', views.list_lab, name='list_lab'),
    url(r'^lab/(?P<pk>[0-9]+)/admin/$', views.list_admin_lab, name='list_admin_lab'),
    url(r'^register/lab/$', views.register_lab, name='register_lab'),
    url(r'^update/lab/(?P<lab_id>[0-9])/$', views.update_lab, name='update_lab'),
    url(r'^deactivate/lab/(?P<lab_id>[0-9])/$', views.deactivate_lab, name='deactivate_lab'),
    url(r'^register/lab/(?P<lab_id>[0-9]+)/admin/$', views.register_lab_admin, name='register_lab_admin'),
    url(r'^update/lab/admin/(?P<pk>[0-9]+)/$', views.update_lab_admin, name='update_lab_admin'),
    url(r'^delete/lab/admin/(?P<pk>[0-9]+)/$', views.deactivate_lab_admin, name='deactivate_lab_admin'),
    url(r'^lab/admin/(?P<pk>[0-9]+)/$', views.detail_lab_admin, name='detail_lab_admin'),
    url('^laboratory/(?P<lab_id>[0-9]+)/$', views.detail_laboratory, name='detail_laboratory'),

    # Other
    url('^filter/$', views.person_filter, name='person_filter')
]

docproject/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url('^grappelli/', include('grappelli.urls')),  # grappelli URLS
    url(r'^admin/', admin.site.urls),
    url(r'', include('docapp.urls', namespace='docapp')),
    url(r'', include('accounts.urls', namespace='accounts')),
    url(r'^labapp/', include('labapp.urls', namespace='labapp')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

labapp/urls.py
from django.conf.urls import url
from labapp import views

urlpatterns = [
    url('^register/personal/$', views.register_personal, name='register_personal'),
    url('^list/examinations/$', views.list_examination_todo, name='list_examination_todo'),
    url('^my/examinations/$', views.lab_own_examinations, name='lab_own_examinations'),
    url('^take/examination/(?P<exam_id>[0-9]+)/$', views.lab_take_a_exam, name='lab_take_a_exam'),
    url('^register/result/(?P<pk>[0-9]+)/$', views.register_lab_exam_result, name='register_lab_exam_result'),
    url('^update/results/(?P<pk>[0-9]+)/$', views.update_lab_exam_result, name='update_lab_exam_result'),
    url('^end/examination/(?P<exam_id>[0-9]+)/$', views.lab_end_exam, name='lab_end_exam'),
    url('^end/examinations/$', views.lab_end_examinations, name='lab_end_examinations')
]

templates/base/base_base.html
<!DOCTYPE html>
<html lang="en">

<!-- Mirrored from healthadmin.thememinister.com/login.html by HTTrack Website Copier/3.x [XR&CO'2014], Sun, 29 Jul 2018 17:30:37 GMT -->
<head>
    {% load static %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>{% block title %} {% endblock %}</title>

    <!-- Favicon and touch icons -->
    <link rel="shortcut icon" href="{% static 'assets/dist/img/ico/favicon.png' %}" type="image/x-icon">
    <!-- Bootstrap -->
    <link href="{% static 'assets/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css"/>
    <!-- Pe-icon-7-stroke -->
    <link href="{% static 'assets/pe-icon-7-stroke/css/pe-icon-7-stroke.css' %}" rel="stylesheet" type="text/css"/>
    <!-- style css -->
    <link href="{% static 'assets/dist/css/stylehealth.min.css' %}" rel="stylesheet" type="text/css"/>
</head>
<body>
{% block main  %}

{% endblock %}

{% block scripts %}
    <!-- /.content-wrapper -->
    <!-- jQuery -->
    <script src="{% static 'assets/plugins/jQuery/jquery-1.12.4.min.js' %}" type="text/javascript"></script>
    <!-- bootstrap js -->
    <script src="{% static 'assets/bootstrap/js/bootstrap.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/utils.js' %}"></script>
{% endblock %}
</body>
</html>

templates/base/base_dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>{% block title %} {% endblock %}</title>
    {% block styles %}
        <!-- Favicon and touch icons -->
        <link rel="shortcut icon" href="{% static 'assets/dist/img/ico/favicon.png' %}" type="image/x-icon">
        <!-- Start Global Mandatory Style -->
        <!-- jquery-ui css -->
        <link href="{% static 'assets/plugins/jquery-ui-1.12.1/jquery-ui.min.css' %}" rel="stylesheet" type="text/css"/>
        <!-- Bootstrap -->
        <link href="{% static 'assets/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css"/>
        <!-- Lobipanel css -->
        <link href="{% static 'assets/plugins/lobipanel/lobipanel.min.css' %}" rel="stylesheet" type="text/css"/>
        <!-- Pace css -->
        <link href="{% static 'assets/plugins/pace/flash.css' %}" rel="stylesheet" type="text/css"/>
        <!--Modal css -->
        <link href="{% static 'assets/plugins/modals/component.css' %}" rel="stylesheet" type="text/css"/>
        <!-- Font Awesome -->
        <link href="{% static 'assets/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css"/>
        <!-- Pe-icon -->
        <link href="{% static 'assets/pe-icon-7-stroke/css/pe-icon-7-stroke.css' %}" rel="stylesheet" type="text/css"/>
        <!-- Themify icons -->
        <link href="{% static 'assets/themify-icons/themify-icons.css' %}" rel="stylesheet" type="text/css"/>
        <!-- Datatable style -->
        <link rel="stylesheet" type="text/css" href="{% static 'assets/plugins/DataTables/datatables.min.css' %}"/>
        <!-- End Global Mandatory Style -->
        <link rel="stylesheet" href="{% static 'assets/plugins/bootstrap-select/bootstrap-select.min.css' %}">
        <!-- Theme style -->
        <link href="{% static 'assets/dist/css/stylehealth.min.css' %}" rel="stylesheet" type="text/css"/>
        <!-- End Theme Layout Style -->
        <style type="text/css">
            .label-custom {
                background-color: #009688;
                border: 2px solid #3a95e4a6;
            }
            {# List striped from  https://markheath.net/post/css-striped-list #}

            ul.striped-list {
                list-style-type: none;
                margin: 0;
                padding: 0;
            }

            ul.striped-list > li:nth-of-type(odd) {
                background-color: #e9e9f9;
            }

            ul.striped-list > li {
                border-bottom: 1px solid rgb(221, 221, 221);
                padding: 6px;
            }

            ul.striped-list > li:last-child {
                border-bottom: none;
            }
        </style>
    {% endblock %}
</head>
<body class="sidebar-mini  pace-done">

<div class="wrapper">
    {% block header %}
        <header class="main-header">
            <a href="#" class="logo"> <!-- Logo -->
                <span class="logo-mini">
                        <img src="{% static 'assets/dist/img/mini-logo.png' %}" alt="">
                    </span>
                <span class="logo-lg">
                        <img src="{% static 'assets/dist/img/logo.png' %}" alt="">
                    </span>
            </a>
            {% include 'base/navbar.html' %}
        </header>
    {% endblock %}

    {% include 'base/sidebar.html' %}

    <div class="content-wrapper" style="min-height: 869px;">


        <!-- Content Header (Page header) -->
        <section class="content-header">
            {% block content_header %}
            {% endblock %}
        </section>


        <!-- Main content -->
        <section class="content">
            {% block content_main %}
            {% endblock %}
        </section>

    </div>

    <footer class="main-footer">
        {% block footer %}

            <div class="pull-right hidden-xs"><b>Version</b> 1.0</div>
            <strong>SM Laboral, Cartagena de Indias</strong> All rights reserved.

        {% endblock %}
    </footer>

</div>

{% block scripts %}
    <!-- Start Core Plugins -->
    <!-- jQuery -->
    <script src="{% static 'assets/plugins/jQuery/jquery-1.12.4.min.js' %}"></script>
    <!-- jquery-ui -->
    <script src="{% static 'assets/plugins/jquery-ui-1.12.1/jquery-ui.min.js' %}"></script>
    <!-- Bootstrap -->
    <script src="{% static 'assets/bootstrap/js/bootstrap.min.js' %}"></script>
    <!-- lobipanel -->
    <script src="{% static 'assets/plugins/lobipanel/lobipanel.min.js' %}"></script>
    <!-- Pace js -->
    <script src="{% static 'assets/plugins/pace/pace.min.js' %}"></script>

    <!-- Modal js -->
    <script src="{% static 'assets/plugins/modals/classie.js' %}"></script>
    <script src="{% static 'assets/plugins/modals/modalEffects.js' %}"></script>
    <!-- End Page Lavel Plugins -->
    <!-- SlimScroll -->
    <script src="{% static 'assets/plugins/slimScroll/jquery.slimscroll.min.js' %}"></script>
    <!-- FastClick -->
    <script src="{% static 'assets/plugins/fastclick/fastclick.min.js' %}"></script>
    <!-- Hadmin frame -->
    <script src="{% static 'assets/dist/js/custom1.js' %}"></script>
    <!-- Datatable plugin -->
    <script src="{% static 'assets/plugins/DataTables/datatables.min.js' %}"></script>
    <!-- Bootstrap Select -->
    <script src="{% static 'assets/plugins/bootstrap-select/bootstrap-select.min.js' %}"></script>
    <!-- End Core Plugins -->
    <!-- Dashboard js -->
    <script src="{% static 'assets/dist/js/custom.js' %}"></script>
    <script src="{% static 'js/utils.js' %}"></script>
{% endblock %}
</body>

</html>

templates/base/base_examination.html
{% extends 'base/base_dashboard.html' %}

{% block title %}  {% endblock %}

{% block content_header %}
    <div class="header-icon">
        <i class="pe-7s-box1"></i>
    </div>
    <div class="header-title">
        <h1>{% block page_title %}Registro Examen {{ exam_name|capfirst }}{% endblock %}</h1>
        <small>{% block small_message %} Ingrese Resultados del proceso #{% if exam %}{{ exam.id }}{% else %}{{ object.examinacion_id_id }}{% endif %}{% endblock %}</small>
        <ol class="breadcrumb hidden-xs">
            <li>
                {% if request.user.doctor_profile %}
                    <a href="{% url 'docapp:doctor_own_examinations' %}" class="active">
                        <i class="pe-7s-home"></i> Lista Examenes</a>
                {% elif request.user.laboratory_profile %}
                    <a href="{% url 'labapp:lab_own_examinations' %}" class="active">
                        <i class="pe-7s-home"></i> Lista Examenes</a>
                {% endif %}
            </li>
        </ol>
    </div>
{% endblock %}

{% block content_main %}
    <div class="container-fuild">
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-sm alert-{% if message.level_tag != 'error' %}{{ message.level_tag }}{% else %}danger{% endif %} alert-dismissible row" role="alert">
                    <div class="text-center col-sm-12">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                                aria-hidden="true">×</span></button>
                        <i class="fa fa-exclamation-circle"></i>
                        <strong>{{ message.level_tag|capfirst }}!</strong> {{ message|escape }}
                    </div>
                </div>
            {% endfor %}
        {% endif %}

        <div class="row">
            <div class="col-sm-12 text-center">
                <small><b>La informacion suministrada en el siguiente formulario sera aplicada al paciente con
                    identificacion {{ exam.paciente_id.identificacion }}</b></small>
            </div>
            <div class="col-sm-12">
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% block form_body %} {% endblock %}
                    <div class="col-sm-12 reset-button">
                        <hr>
                        <button type="submit" class="btn btn-success">Guardar</button>
                    </div>
                </form>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

templates/base/base_list.html
{% extends 'base/base_dashboard.html' %}
{% load static %}
{% block title %} {% endblock %}


{% block content_header %}
    <div class="header-icon">
        <i class="pe-7s-box1"></i>
    </div>
    <div class="header-title">
        <form action="#" method="get" class="sidebar-form search-box pull-right hidden-md hidden-lg hidden-sm">
            <div class="input-group">
                <input name="q" class="form-control" placeholder="Search..." type="text">
                <span class="input-group-btn">
                                    <button type="submit" name="search" id="search-btn" class="btn"><i
                                            class="fa fa-search"></i></button>
                                </span>
            </div>
        </form>
        <h1>{% block page_title %}{% endblock %}</h1>
        <small>{% block small_message %}{% endblock %}</small>
    </div>
{% endblock %}

{% block content_main %}
    <div class="container-fluid">
        <!-- Header -->
        <div class="row">
            <div class="col-sm-12">
                <div class="btn-group">
                    {% block add_btn %}
                        <a class="btn btn-success" href="{% block add_link %}{% endblock %}"> <i
                                class="fa fa-plus"></i>{% block add_link_label %}{% endblock %}</a>
                    {% endblock %}
                </div>
            </div>
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-sm alert-{% if message.level_tag != 'error' %}{{ message.level_tag }}{% else %}danger{% endif %} alert-dismissible col-sm-12 m-t-20"
                         role="alert">
                        <div class="text-center">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                                    aria-hidden="true">×</span></button>
                            <i class="fa fa-exclamation-circle"></i>
                            <strong>{{ message.level_tag|capfirst }}!</strong> {{ message|escape }}
                        </div>
                    </div>
                {% endfor %}
            {% endif %}
        </div>
        <hr>
        <!-- DataTable Body -->
        <div class="row">
            <div class="table-responsive">
                <table class="table table-bordered table-hover text-center" id="TableMain">
                    {% block datatable_body %} {% endblock %}
                </table>
            </div>

        </div>
    {% block extra_content %}{% endblock %}

    </div>
{% endblock %}
{% block scripts %}
    {{ block.super }}
    <script type="text/javascript">
        $(document).ready(function (){
            $('#TableMain').DataTable({})
        });
    </script>
    {% block extra_scripts %}{% endblock %}
{% endblock %}

templates/base/base_modal.html
<div class="modal" id="base_modal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title"></h4>
            </div>
            <div class="modal-body"></div>
            <div class="modal-footer">
                <div class="col-sm-12">
                    <button type="button" class="btn btn-danger" data-dismiss="modal">Cerrar</button>
                </div>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

templates/base/navbar.html
{% load static %}
<nav class="navbar navbar-static-top ">
    <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button"> <!-- Sidebar toggle button-->
        <span class="sr-only">Toggle navigation</span>
        <span class="fa fa-tasks"></span>
    </a>
    <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">
            <!-- user -->
            <li class="dropdown dropdown-user admin-user">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    <div class="user-image">
                        <img src="{{ user.avatar.url }}" class="img-circle" height="40" width="40"
                             alt="User Image">
                    </div>
                </a>
                <ul class="dropdown-menu">
                    <li><a href="{% url 'accounts:show_profile' %}">
                        <i class="fa fa-users"></i>Perfil</a>
                    </li>
                    <li>
                        <a href="{% url 'accounts:logout' %}">
                            <i class="fa fa-sign-out"></i> Cerrar Sesión
                        </a>
                    </li>
                </ul>
            </li>
        </ul>
    </div>
</nav>

templates/base/sidebar.html
<!-- =============================================== -->
<!-- Left side column. contains the sidebar -->
{% load static %}
<aside class="main-sidebar">
    <!-- sidebar -->
    <div class="sidebar">
        <!-- Sidebar user panel -->
        <div class="user-panel">
            <div class="image pull-left">
                <img src="{{ user.avatar.url }}" class="img-circle" alt="User Image">
            </div>
            <div class="info">
                <h4>Bienvenido</h4>
                <p>{{ request.user.get_full_name }}</p>
            </div>
        </div>

        <!-- sidebar menu -->
        <ul class="sidebar-menu">
            <li class="active">
                <a href="{% url 'docapp:dashboard' %}"><i class="fa fa-hospital-o"></i><span>Dashboard</span></a>
            </li>
            {% if request.user.profile_type == 'p_laboratorio' %}
                {% if request.user.laboratory_profile.is_admin %}
                    <!-- Personal options -->
                    <li class="treeview">
                        <a href="#">
                            <i class="fa fa-user-circle-o"></i><span>Recursos Humanos</span>
                            <span class="pull-right-container"><i class="fa fa-angle-left pull-right"></i></span>
                        </a>
                        <ul class="treeview-menu">
                            <li><a href="#">Añadir Empleado</a></li>
                            <li><a href="#">Lista Empleados</a></li>
                        </ul>
                    </li>
                {% endif %}
            {% endif %}

            {% if request.user.is_superuser %}
                <!-- Personal options -->
                <li class="treeview">
                    <a href="#">
                        <i class="fa fa-user-circle-o"></i><span>Recursos Humanos</span>
                        <span class="pull-right-container"><i class="fa fa-angle-left pull-right"></i></span>
                    </a>
                    <ul class="treeview-menu">
                        <li><a href="{% url 'accounts:register_personal' %}">Añadir Empleado</a></li>
                        <li><a href="{% url 'accounts:user_list' %}">Lista Empleados</a></li>
                    </ul>
                </li>
            {% endif %}

            {% if request.user.profile_type == 'receptionista' %}
                <!-- Enterprise options -->
                <li class="treeview">
                    <a href="#">
                        <i class="fa fa-building"></i><span>Empresas</span>
                        <span class="pull-right-container"><i class="fa fa-angle-left pull-right"></i></span>
                    </a>
                    <ul class="treeview-menu">
                        <li><a href="{% url 'docapp:list_company' %}">Lista</a></li>
                        <li><a href="{% url 'docapp:register_company' %}">Registrar</a></li>
                    </ul>
                </li>

                <!-- Lab options -->
                <li class="treeview">
                    <a href="#">
                        <i class="fa fa-flask"></i><span>Laboratorios</span>
                        <span class="pull-right-container"><i class="fa fa-angle-left pull-right"></i></span>
                    </a>
                    <ul class="treeview-menu">
                        <li><a href="{% url 'docapp:list_lab' %}">Lista</a></li>
                        <li><a href="{% url 'docapp:register_lab' %}">Registrar</a></li>
                    </ul>
                </li>

                <!-- Independent Employees options -->
                <li class="treeview">
                    <a href="#">
                        <i class="fa fa-user"></i><span>Independientes</span>
                        <span class="pull-right-container"><i class="fa fa-angle-left pull-right"></i></span>
                    </a>
                    <ul class="treeview-menu">
                        <li><a href="{% url 'docapp:list_independent_employ' %}">Lista</a></li>
                        <li><a href="{% url 'docapp:register_employ_without_company' %}">Registrar</a></li>
                    </ul>
                </li>

                <!-- Particular Employees options -->
                <li class="treeview">
                    <a href="#">
                        <i class="fa fa-user"></i><span>Particular</span>
                        <span class="pull-right-container"><i class="fa fa-angle-left pull-right"></i></span>
                    </a>
                    <ul class="treeview-menu">
                        <li><a href="{% url 'docapp:list_simple_patient' %}">Lista</a></li>
                        <li><a href="{% url 'docapp:register_simple_patient' %}">Registrar</a></li>
                    </ul>
                </li>
            {% endif %}


            {% if request.user.profile_type %}
                <!-- Examinations-->
                <li class="treeview">
                    <a href="#">
                        <i class="fa fa-flask"></i><span>Consultas</span>
                        <span class="pull-right-container"><i class="fa fa-angle-left pull-right"></i></span>
                    </a>
                    <ul class="treeview-menu">
                        <li>
                            {% if request.user.profile_type == 'doctor' %}
                                <a href="{% url 'docapp:enable_consults' %}">Disponibles</a>
                            {% elif request.user.profile_type == 'receptionista' %}
                                <a href="{% url 'docapp:list_consults' %}">Lista</a>
                            {% endif %}
                        </li>

                        {% if request.user.profile_type == 'doctor' %}
                            <li><a href="{% url 'docapp:list_own_consults' %}">Pendientes</a></li>
                            <li><a href="{%  url 'docapp:list_end_consults' %}">Finalizadas</a></li>
                        {% endif %}
                    </ul>
                </li>

                 <li class="treeview">
                    <a href="#">
                        <i class="fa fa-flask"></i><span>Examinaciones</span>
                        <span class="pull-right-container"><i class="fa fa-angle-left pull-right"></i></span>
                    </a>
                    <ul class="treeview-menu">
                        <li>
                            {% if request.user.profile_type == 'p_laboratorio' %}
                                <a href="{% url 'labapp:list_examination_todo' %}">Disponibles</a>
                            {% elif request.user.profile_type == 'doctor' %}
                                <a href="{% url 'docapp:list_examination' %}">Disponibles</a>
                            {% elif request.user.profile_type == 'receptionista' %}
                                <a href="{% url 'docapp:list_examination' %}">Lista</a>
                            {% endif %}
                        </li>
                        {% if request.user.profile_type == 'p_laboratorio' %}
                            <li><a href="{% url 'labapp:lab_own_examinations' %}">Pendientes</a></li>
                            <li><a href="{% url 'labapp:lab_end_examinations' %}">Finalizadas</a></li>
                        {% elif request.user.profile_type == 'doctor' %}
                            <li><a href="{% url 'docapp:doctor_own_examinations' %}">Pendientes</a></li>
                            <li><a href="{% url 'docapp:doctor_end_examinations' %}">Finalizadas</a></li>
                        {% endif %}
                    </ul>
                </li>
            {% endif %}


        </ul>
    </div>
</aside>