docapp/urls.py
from django.conf.urls import url
from docapp import views

urlpatterns = [
    url(r'^dashboard/$', views.dashboard, name='dashboard'),
    # Company urls
    url(r'^company/$', views.list_company, name='list_company'),
    url(r'^company/(?P<company_id>[0-9]+)/$', views.detail_company, name='detail_company'),
    url(r'^register/company/$', views.register_company, name='register_company'),
    url(r'^update/company/(?P<company_id>[0-9]+)/$', views.update_company, name='update_company'),
    url(r'^employs/company/(?P<company_id>[0-9])+/$', views.list_employ_company, name='list_employ_company'),

    # Employ urls
    url(r'^person/$', views.list_independent_employ, name='list_independent_employ'),
    url(r'^person/(?P<person_id>[0-9]+)/$', views.detail_employ, name='detail_employ'),
    url(r'^register/person/$', views.register_employ_without_company, name='register_employ_without_company'),
    url(r'^register/person/(?P<company_id>[0-9]+)/$', views.register_employ_from_company,
        name='register_employ_from_company'),
    url(r'^update/person/(?P<person_id>[0-9]+)/$', views.update_employ, name='update_employ'),

    # Particular urls
    url(r'^patient/$', views.list_simple_patient, name='list_simple_patient'),
    url(r'^patient/(?P<pk>[0-9]+)/$', views.detail_patient, name='detail_patient'),
    url(r'^register/patient/$', views.register_simple_patient, name='register_simple_patient'),
    url(r'^update/patient/(?P<pk>[0-9]+)/$', views.update_simple_patient, name='update_simple_patient'),

    # Consults urls
    url(r'^consult/$', views.make_consulta, name='make_consult'),
    url(r'^assign_consult/$', views.assign_consult, name='assign_consult'),
    url(r'^enable_consults/$', views.list_consults_enable, name='enable_consults'),
    url(r'^consults/$', views.list_consults, name='list_consults'),
    url(r'^own_consults/$', views.lab_own_consults, name='list_own_consults'),
    url(r'^end_consult/$', views.end_consult, name='end_consult'),
    url(r'^list_end_consult/$', views.list_end_consults, name='list_end_consults'),


    # Antecedent urls
    url(r'^antecedent/(?P<person_id>[0-9])/$', views.list_employ_antecedents, name='list_employ_antecedents'),
    url(r'^antecedent/detail/(?P<antecedent_id>[0-9]+)/$', views.detail_employ_antecedent,
        name='detail_employ_antecedent'),
    url(r'^register/antecedent/(?P<person_id>[0-9]+)/$', views.register_employ_antecedent,
        name='register_employ_antecedent'),
    url(r'^update/antecedent/(?P<antecedent_id>[0-9]+)/$', views.update_employ_antecedent,
        name='update_employ_antecedent'),

    # Examination urls
    url(r'^register/exam/(?P<person_id>[0-9]+)/$', views.register_employ_examination,
        name='register_employ_examination'),
    url(r'^examination/$', views.list_examination, name='list_examination'),
    url(r'^examination/(?P<exam_id>[0-9]+)/$', views.detail_examination, name='detail_examination'),
    url(r'^take/examination/(?P<exam_id>[0-9]+)/$', views.take_a_exam, name='doctor_take_a_exam'),
    url(r'^my/examinations/$', views.own_examinations, name='doctor_own_examinations'),
    url(r'^end/examination/(?P<exam_id>[0-9]+)/$', views.doctor_end_exam, name='doctor_end_exam'),
    url(r'^end/examinations/$', views.end_examinations, name='doctor_end_examinations'),


    # Registro de examanes
    url(r'^register/(?P<exam_id>[0-9]+)/occupational/$', views.register_occupational, name='register_occupational'),
    url(r'^register/(?P<exam_id>[0-9]+)/audiology/$', views.register_audiology, name='register_audiology'),
    url(r'^register/(?P<exam_id>[0-9]+)/visiometry/$', views.register_visiometry, name='register_visiometry'),
    url(r'^register/(?P<exam_id>[0-9]+)/altura/$', views.register_altura, name='register_altura'),

    # Update exams
    url(r'^occupational/(?P<pk>[0-9]+)/$', views.update_ocupacional, name='update_ocupacional'),
    url(r'^audiology/(?P<pk>[0-9]+)/$', views.update_audiologia, name='update_audiologia'),
    url(r'^visiometry/(?P<pk>[0-9]+)/$', views.update_visiometria, name='update_visiometria'),
    url(r'^altura/(?P<pk>[0-9]+)/$', views.update_altura, name='update_altura'),
    url(r'^simple_exam/(?P<pk>[0-9]+)/$', views.register_simple_exam, name='register_simple_exam'),

    # Lab urls
    url(r'^labs/$', views.list_lab, name='list_lab'),
    url(r'^lab/(?P<pk>[0-9]+)/admin/$', views.list_admin_lab, name='list_admin_lab'),
    url(r'^register/lab/$', views.register_lab, name='register_lab'),
    url(r'^update/lab/(?P<lab_id>[0-9])/$', views.update_lab, name='update_lab'),
    url(r'^deactivate/lab/(?P<lab_id>[0-9])/$', views.deactivate_lab, name='deactivate_lab'),
    url(r'^register/lab/(?P<lab_id>[0-9]+)/admin/$', views.register_lab_admin, name='register_lab_admin'),
    url(r'^update/lab/admin/(?P<pk>[0-9]+)/$', views.update_lab_admin, name='update_lab_admin'),
    url(r'^delete/lab/admin/(?P<pk>[0-9]+)/$', views.deactivate_lab_admin, name='deactivate_lab_admin'),
    url(r'^lab/admin/(?P<pk>[0-9]+)/$', views.detail_lab_admin, name='detail_lab_admin'),
    url('^laboratory/(?P<lab_id>[0-9]+)/$', views.detail_laboratory, name='detail_laboratory'),

    # Other
    url('^filter/$', views.person_filter, name='person_filter')
]

docproject/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url('^grappelli/', include('grappelli.urls')),  # grappelli URLS
    url(r'^admin/', admin.site.urls),
    url(r'', include('docapp.urls', namespace='docapp')),
    url(r'', include('accounts.urls', namespace='accounts')),
    url(r'^labapp/', include('labapp.urls', namespace='labapp')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

labapp/urls.py
from django.conf.urls import url
from labapp import views

urlpatterns = [
    url('^register/personal/$', views.register_personal, name='register_personal'),
    url('^list/examinations/$', views.list_examination_todo, name='list_examination_todo'),
    url('^my/examinations/$', views.lab_own_examinations, name='lab_own_examinations'),
    url('^take/examination/(?P<exam_id>[0-9]+)/$', views.lab_take_a_exam, name='lab_take_a_exam'),
    url('^register/result/(?P<pk>[0-9]+)/$', views.register_lab_exam_result, name='register_lab_exam_result'),
    url('^update/results/(?P<pk>[0-9]+)/$', views.update_lab_exam_result, name='update_lab_exam_result'),
    url('^end/examination/(?P<exam_id>[0-9]+)/$', views.lab_end_exam, name='lab_end_exam'),
    url('^end/examinations/$', views.lab_end_examinations, name='lab_end_examinations')
]

labapp/forms.py
from django import forms
from django.db import IntegrityError

from accounts.forms import BaseUserForm

from labapp.models import Laboratorio, LaboratoryProfile, LabExam, ExamResults


class BaseLabUserCreateForm(BaseUserForm):

    class Meta(BaseUserForm.Meta):
        exclude = ('profile_type', )

    def save(self, commit=True, **info):
        instance = super(BaseUserForm, self).save(commit=False)
        # Set clean password to user to save
        instance.password = self.cleaned_data.get('password2')
        instance.profile_type = 'p_laboratorio'  # Set laboratory profile
        if commit:
            instance.save()
            # Save profile now
            try:
                info.update({'user_id': instance})
                laboratory = LaboratoryProfile(**info)
                laboratory.save()
            except IntegrityError:
                instance.delete(destroy=True)
                raise forms.ValidationError(message="Unable to save profile, check information", code='invalid')
        return instance


lab_exam_result = forms.inlineformset_factory(parent_model=LabExam, model=ExamResults, extra=1, can_delete=True,
                                              fields='__all__', exclude=('examen', ))

labapp/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic import FormView, ListView, TemplateView, DetailView
from django.core.urlresolvers import reverse_lazy
from django.db.models import Q, Count
from django.views.generic.detail import SingleObjectMixin
from django.db import IntegrityError
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.shortcuts import reverse, redirect
from django import forms

from docapp.choices import ExamStates
from docproject.helpers.chekers import CheckLaboratory

from labapp.forms import BaseLabUserCreateForm, lab_exam_result
from docapp.models import Examinacion, Consulta
from labapp.models import LabExam, ExamResults, Laboratorio
from labapp.mixins import PostResultManager


class RegisterPersonal(LoginRequiredMixin, CheckLaboratory, SuccessMessageMixin, FormView):
    form_class = BaseLabUserCreateForm
    success_url = reverse_lazy('docapp:dashboard')
    success_message = 'Personal de laboratorio registrado exitosamente'


register_personal = RegisterPersonal.as_view()


class ListExaminationWithouLab(LoginRequiredMixin, CheckLaboratory, ListView):
    model = Examinacion
    context_object_name = 'exam_list'
    template_name = 'docapp/lists/exam_list.html'

    def get_queryset(self):
        user_lab = self.request.user.laboratory_profile.laboratorio_id
        queryset = Examinacion.objects.filter(
            Q(examenes_laboratorios__laboratorio_id=user_lab) & Q(examenes_laboratorios__manejado_por=None)
        ).annotate(dcount=Count('tipo'))
        return queryset


list_examination_todo = ListExaminationWithouLab.as_view()

# Views to process a examination process
class ListOwnExams(LoginRequiredMixin, CheckLaboratory, ListView):
    model = Examinacion
    context_object_name = 'exam_list'
    template_name = 'docapp/lists/exam_list.html'

    def get_queryset(self):
        user_lab = self.request.user.laboratory_profile.laboratorio_id
        user = self.request.user.laboratory_profile
        queryset = Examinacion.objects.filter(
            Q(examenes_laboratorios__laboratorio_id=user_lab) & Q(examenes_laboratorios__manejado_por=user)
        ).annotate(dcount=Count('tipo')).exclude(lab_estado=ExamStates.FINALIZADO)
        # Simulate group by clause -- https://stackoverflow.com/questions/629551/how-to-query-as-group-by-in-django
        # https://docs.djangoproject.com/en/dev/topics/db/aggregation/#topics-db-aggregation
        return queryset


lab_own_examinations = ListOwnExams.as_view()


class LabTakeAExam(LoginRequiredMixin, CheckLaboratory, SingleObjectMixin, TemplateView):
    object = None
    pk_url_kwarg = 'exam_id'
    model = Examinacion
    template_name = 'labapp/take_exam.html'
    redirect_url = reverse_lazy('labapp:lab_own_examinations')

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        kwargs.update({'redirect_url': self.redirect_url})
        return super(LabTakeAExam, self).get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        exam = self.get_object()
        exam.lab_estado = ExamStates.ASIGNADO
        exam.save()
        for lab_exam in exam.examenes_laboratorios.all():
            lab_exam.manejado_por = request.user.laboratory_profile
            try:
                lab_exam.save(update_state=False)
            except IntegrityError as e:
                print("Error save infor -> {}".format(e))
                messages.error(message='Examinacion NO Asignada', request=request)
                break
        else:
            messages.success(message='Examinacion Asignada Exitosamente', request=request)
        return HttpResponseRedirect(reverse('labapp:lab_own_examinations'))


lab_take_a_exam = LabTakeAExam.as_view()


class RegisterLabExamResult(LoginRequiredMixin, CheckLaboratory, PostResultManager, DetailView):
    model = LabExam
    context_object_name = 'exam'
    template_name = 'labapp/register/labexam_result.html'
    result_formset = lab_exam_result

    def get_context_data(self, **kwargs):
        if kwargs.get('result_formset') is None:
            kwargs.update({'result_formset': self.result_formset})
        return super(RegisterLabExamResult, self).get_context_data(**kwargs)

    def get(self, request, *args, **kwargs):
        results = ExamResults.objects.filter(examen=self.get_object()) or None
        if results:
            return HttpResponseRedirect(reverse('labapp:update_lab_exam_result', kwargs=kwargs))
        return super(RegisterLabExamResult, self).get(request, *args, **kwargs)


register_lab_exam_result = RegisterLabExamResult.as_view()


class UpdateLabExamResult(LoginRequiredMixin, CheckLaboratory, PostResultManager, DetailView):
    model = LabExam
    context_object_name = 'exam'
    template_name = 'labapp/register/labexam_result.html'
    result_formset = lab_exam_result

    def get_context_data(self, **kwargs):
        if kwargs.get('result_formset') is None:
            results = ExamResults.objects.filter(examen=self.get_object())
            data_key = ('prueba', 'referencias', 'resultados',)
            initial_data = []
            for result in results:
                all_dict = vars(result)
                data = {key: value for key, value in all_dict.items() if key in data_key}
                initial_data.append(data)

            result_formset = forms.inlineformset_factory(parent_model=LabExam, model=ExamResults, fields='__all__',
                                                         extra=len(initial_data), can_delete=True, exclude=('examen',))
            kwargs.update({'result_formset': result_formset(initial=initial_data)})
        return super(UpdateLabExamResult, self).get_context_data(**kwargs)


update_lab_exam_result = UpdateLabExamResult.as_view()


class LabEndExam(LoginRequiredMixin, CheckLaboratory, SingleObjectMixin, TemplateView):
    object = None
    pk_url_kwarg = 'exam_id'
    model = Examinacion
    template_name = 'docapp/end_process.html'

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super(LabEndExam, self).get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        exam = self.get_object()
        if exam.get_lab_process() == 100:
            exam.lab_estado = ExamStates.FINALIZADO
            try:
                exam.save()
            except IntegrityError:
                messages.error(message='Examinacion NO Terminada', request=request)
            else:
                messages.success(message='Examinacion Asignada Exitosamente', request=request)
            return redirect('labapp:lab_end_examinations')
        else:
            messages.warning(request, "No ha terminado todos los examenes")
            return redirect(request.path)


lab_end_exam = LabEndExam.as_view()


class ListEndExams(LoginRequiredMixin, CheckLaboratory, ListView):
    model = Examinacion
    context_object_name = 'exam_list'
    template_name = 'docapp/lists/exam_list.html'

    def get_queryset(self):
        user_lab = self.request.user.laboratory_profile.laboratorio_id
        user = self.request.user.laboratory_profile
        queryset = Examinacion.objects.filter(
            Q(examenes_laboratorios__laboratorio_id=user_lab) & Q(examenes_laboratorios__manejado_por=user) &
            Q(lab_estado='finalizado')
        ).annotate(dcount=Count('tipo'))
        # Simulate group by clause -- https://stackoverflow.com/questions/629551/how-to-query-as-group-by-in-django
        # https://docs.djangoproject.com/en/dev/topics/db/aggregation/#topics-db-aggregation
        return queryset


lab_end_examinations = ListEndExams.as_view()

templates/labapp/list/admins.html
{% extends 'base/base_list.html' %}
{% load static %}
{% block title %} Lista Lab Admin {% endblock %}

{% block page_title %}Administradores de {{ lab }} {% endblock %}
{% block small_message %} Lista de usuarios administradores del laboratorio {{ lab }} {% endblock %}
{% block add_link %} {% url 'docapp:register_lab_admin' lab_id=lab.id %} {% endblock %}
{% block add_link_label %} Administrador {% endblock %}


{% block datatable_body %}
    <thead>
    <tr>
        <th>Nombre</th>
        <th>Opciones</th>
        <th>Estado</th>
    </tr>
    </thead>
    <tbody>
    {% for object in admin_lab_list %}
        <tr>
            <td>{{ object }}</td>
            <td>
                <!-- Detail Link -->
                <button class="btn btn-primary btn-xs btn_modal" data-modal-title="Detalle Lab Admin"
                        href="{% url 'docapp:detail_lab_admin' pk=object.user_id.id %}">
                    Ver <i class="fa fa-eye" aria-hidden="true"></i>
                </button>
                <!-- Update Link -->
                <a href="{% url 'docapp:update_lab_admin' pk=object.user_id.id %}">
                    <button class="btn btn-warning btn-xs" data-toggle="tooltip"
                            data-placement="left" title="" data-original-title="Editar">
                        <i class="fa fa-edit" aria-hidden="true"></i> Editar
                    </button>
                </a>
                {% if object.user_id.is_active %}
                    <!-- Deactivate Link -->
                    <button class="btn btn-danger btn-xs btn_modal" data-toggle="tooltip"
                            data-modal-title="Desactivar Admin"
                            data-placement="right" title="" data-original-title="Desactivar"
                            href="{% url 'docapp:deactivate_lab_admin' pk=object.user_id.id %}">
                        <i class="fa fa-trash-o" aria-hidden="true"></i>
                    </button>
                {% endif %}
            </td>
            <td>{% if object.user_id.is_active %}
                <span class="label label-success">Activo</span>
            {% else %}
                <span class="label label-danger">Desactivado</span>
            {% endif %}</td>

        </tr>
    {% empty %}
        <h1>No se encuentra ningun laboratorio registrado</h1>
    {% endfor %}
    </tbody>
{% endblock %}
{% block extra_content %}
    {% include 'base/base_modal.html' %}
{% endblock %}
{% block extra_scripts %}
    <script>
        $('.btn_modal').on('click', function (event) {
            event.preventDefault();
            event.stopPropagation();
            load_modal(this.dataset.modalTitle, "success", this.getAttribute('href'));
        });
    </script>
{% endblock %}

templates/labapp/list/laboratory.html
{% extends 'base/base_list.html' %}
{% load static %}
{% block title %} Lista Empleados {% endblock %}

{% block page_title %}Empresas {% endblock %}
{% block small_message %} Lista de Empresas {% endblock %}
{% block add_link %} {% url 'docapp:register_lab' %} {% endblock %}
{% block add_link_label %} Laboratorio {% endblock %}


{% block datatable_body %}
    <thead>
    <tr>
        <th>Nombre</th>
        <th>Administradores</th>
        <th>Opciones</th>
        <th>Estado</th>
    </tr>
    </thead>
    <tbody>
    {% for object in object_list %}
        <tr>
            <td>{{ object }}</td>
            <td>
                <!-- Register Link -->
                <a href="{% url 'docapp:register_lab_admin' lab_id=object.id %}">
                    <button class="btn btn-warning btn-xs" data-toggle="tooltip"
                            data-placement="left" title="" data-original-title="Registrar">
                        Registro <i class="fa fa-pencil" aria-hidden="true"></i>
                    </button>
                </a>
                <!-- List Link -->
                <a href="{% url 'docapp:list_admin_lab' pk=object.id %}">
                    <button class="btn btn-primary btn-xs">
                        <i class="fa fa-list-alt" aria-hidden="true"></i> Lista
                    </button>
                </a>
            </td>
            <td>
                <!-- Detail Link -->
                <button class="btn btn-primary btn-xs btn_modal" data-modal-title="Detalle Laboratorio"
                        href="{% url 'docapp:detail_laboratory' lab_id=object.id %}">
                    Ver <i class="fa fa-eye" aria-hidden="true"></i>
                </button>
                <!-- Update Link -->
                <a href="{% url 'docapp:update_lab' lab_id=object.id %}">
                    <button class="btn btn-warning btn-xs">
                        <i class="fa fa-edit" aria-hidden="true"></i> Editar
                    </button>
                </a>
                {% if object.is_active %}
                    <!-- Deactivate Link -->
                    <button class="btn btn-danger btn-xs btn_modal" data-toggle="tooltip"
                            data-placement="right" data-modal-title="Desactivar Usuario"
                            data-original-title="Desactivar"
                            href="{% url 'docapp:deactivate_lab' lab_id=object.id %}">
                        <i class="fa fa-trash-o" aria-hidden="true"></i>
                    </button>
                {% endif %}
            </td>
            <td>{% if object.is_active %}
                <span class="label label-success">Activo</span>
            {% else %}
                <span class="label label-danger">Desactivado</span>
            {% endif %}</td>
        </tr>
    {% endfor %}
    </tbody>
{% endblock %}
{% block extra_content %}
    {% include 'base/base_modal.html' %}
{% endblock %}
{% block extra_scripts %}
    <script>
        $('.btn_modal').on('click', function (event) {
            event.preventDefault();
            load_modal(this.dataset.modalTitle, "success", this.getAttribute('href'));
        });
    </script>
{% endblock %}