docapp/urls.py
from django.conf.urls import url
from docapp import views

urlpatterns = [
    url(r'^dashboard/$', views.dashboard, name='dashboard'),
    # Company urls
    url(r'^company/$', views.list_company, name='list_company'),
    url(r'^company/(?P<company_id>[0-9]+)/$', views.detail_company, name='detail_company'),
    url(r'^register/company/$', views.register_company, name='register_company'),
    url(r'^update/company/(?P<company_id>[0-9]+)/$', views.update_company, name='update_company'),
    url(r'^employs/company/(?P<company_id>[0-9])+/$', views.list_employ_company, name='list_employ_company'),

    # Employ urls
    url(r'^person/$', views.list_independent_employ, name='list_independent_employ'),
    url(r'^person/(?P<person_id>[0-9]+)/$', views.detail_employ, name='detail_employ'),
    url(r'^register/person/$', views.register_employ_without_company, name='register_employ_without_company'),
    url(r'^register/person/(?P<company_id>[0-9]+)/$', views.register_employ_from_company,
        name='register_employ_from_company'),
    url(r'^update/person/(?P<person_id>[0-9]+)/$', views.update_employ, name='update_employ'),

    # Particular urls
    url(r'^patient/$', views.list_simple_patient, name='list_simple_patient'),
    url(r'^patient/(?P<pk>[0-9]+)/$', views.detail_patient, name='detail_patient'),
    url(r'^register/patient/$', views.register_simple_patient, name='register_simple_patient'),
    url(r'^update/patient/(?P<pk>[0-9]+)/$', views.update_simple_patient, name='update_simple_patient'),

    # Consults urls
    url(r'^consult/$', views.make_consulta, name='make_consult'),
    url(r'^assign_consult/$', views.assign_consult, name='assign_consult'),
    url(r'^enable_consults/$', views.list_consults_enable, name='enable_consults'),
    url(r'^consults/$', views.list_consults, name='list_consults'),
    url(r'^own_consults/$', views.lab_own_consults, name='list_own_consults'),
    url(r'^end_consult/$', views.end_consult, name='end_consult'),
    url(r'^list_end_consult/$', views.list_end_consults, name='list_end_consults'),


    # Antecedent urls
    url(r'^antecedent/(?P<person_id>[0-9])/$', views.list_employ_antecedents, name='list_employ_antecedents'),
    url(r'^antecedent/detail/(?P<antecedent_id>[0-9]+)/$', views.detail_employ_antecedent,
        name='detail_employ_antecedent'),
    url(r'^register/antecedent/(?P<person_id>[0-9]+)/$', views.register_employ_antecedent,
        name='register_employ_antecedent'),
    url(r'^update/antecedent/(?P<antecedent_id>[0-9]+)/$', views.update_employ_antecedent,
        name='update_employ_antecedent'),

    # Examination urls
    url(r'^register/exam/(?P<person_id>[0-9]+)/$', views.register_employ_examination,
        name='register_employ_examination'),
    url(r'^examination/$', views.list_examination, name='list_examination'),
    url(r'^examination/(?P<exam_id>[0-9]+)/$', views.detail_examination, name='detail_examination'),
    url(r'^take/examination/(?P<exam_id>[0-9]+)/$', views.take_a_exam, name='doctor_take_a_exam'),
    url(r'^my/examinations/$', views.own_examinations, name='doctor_own_examinations'),
    url(r'^end/examination/(?P<exam_id>[0-9]+)/$', views.doctor_end_exam, name='doctor_end_exam'),
    url(r'^end/examinations/$', views.end_examinations, name='doctor_end_examinations'),


    # Registro de examanes
    url(r'^register/(?P<exam_id>[0-9]+)/occupational/$', views.register_occupational, name='register_occupational'),
    url(r'^register/(?P<exam_id>[0-9]+)/audiology/$', views.register_audiology, name='register_audiology'),
    url(r'^register/(?P<exam_id>[0-9]+)/visiometry/$', views.register_visiometry, name='register_visiometry'),
    url(r'^register/(?P<exam_id>[0-9]+)/altura/$', views.register_altura, name='register_altura'),

    # Update exams
    url(r'^occupational/(?P<pk>[0-9]+)/$', views.update_ocupacional, name='update_ocupacional'),
    url(r'^audiology/(?P<pk>[0-9]+)/$', views.update_audiologia, name='update_audiologia'),
    url(r'^visiometry/(?P<pk>[0-9]+)/$', views.update_visiometria, name='update_visiometria'),
    url(r'^altura/(?P<pk>[0-9]+)/$', views.update_altura, name='update_altura'),
    url(r'^simple_exam/(?P<pk>[0-9]+)/$', views.register_simple_exam, name='register_simple_exam'),

    # Lab urls
    url(r'^labs/$', views.list_lab, name='list_lab'),
    url(r'^lab/(?P<pk>[0-9]+)/admin/$', views.list_admin_lab, name='list_admin_lab'),
    url(r'^register/lab/$', views.register_lab, name='register_lab'),
    url(r'^update/lab/(?P<lab_id>[0-9])/$', views.update_lab, name='update_lab'),
    url(r'^deactivate/lab/(?P<lab_id>[0-9])/$', views.deactivate_lab, name='deactivate_lab'),
    url(r'^register/lab/(?P<lab_id>[0-9]+)/admin/$', views.register_lab_admin, name='register_lab_admin'),
    url(r'^update/lab/admin/(?P<pk>[0-9]+)/$', views.update_lab_admin, name='update_lab_admin'),
    url(r'^delete/lab/admin/(?P<pk>[0-9]+)/$', views.deactivate_lab_admin, name='deactivate_lab_admin'),
    url(r'^lab/admin/(?P<pk>[0-9]+)/$', views.detail_lab_admin, name='detail_lab_admin'),
    url('^laboratory/(?P<lab_id>[0-9]+)/$', views.detail_laboratory, name='detail_laboratory'),

    # Other
    url('^filter/$', views.person_filter, name='person_filter')
]

docproject/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url('^grappelli/', include('grappelli.urls')),  # grappelli URLS
    url(r'^admin/', admin.site.urls),
    url(r'', include('docapp.urls', namespace='docapp')),
    url(r'', include('accounts.urls', namespace='accounts')),
    url(r'^labapp/', include('labapp.urls', namespace='labapp')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

labapp/urls.py
from django.conf.urls import url
from labapp import views

urlpatterns = [
    url('^register/personal/$', views.register_personal, name='register_personal'),
    url('^list/examinations/$', views.list_examination_todo, name='list_examination_todo'),
    url('^my/examinations/$', views.lab_own_examinations, name='lab_own_examinations'),
    url('^take/examination/(?P<exam_id>[0-9]+)/$', views.lab_take_a_exam, name='lab_take_a_exam'),
    url('^register/result/(?P<pk>[0-9]+)/$', views.register_lab_exam_result, name='register_lab_exam_result'),
    url('^update/results/(?P<pk>[0-9]+)/$', views.update_lab_exam_result, name='update_lab_exam_result'),
    url('^end/examination/(?P<exam_id>[0-9]+)/$', views.lab_end_exam, name='lab_end_exam'),
    url('^end/examinations/$', views.lab_end_examinations, name='lab_end_examinations')
]

docapp/views/doctor.py
from django import forms
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db import IntegrityError
from django.db.models import Count, Q, F
from django.http import HttpResponseRedirect
from django.shortcuts import redirect
from django.views.decorators.http import require_POST
from django.views.generic import UpdateView, DetailView, TemplateView, ListView
from django.core.exceptions import ObjectDoesNotExist, SuspiciousOperation
from django.core.urlresolvers import reverse_lazy
from django.contrib import messages
from django.views.generic.detail import SingleObjectMixin

from docapp.models import (PacienteEmpresa, Occupational, Audiology, Visiometry, Altura, AntecedentesLaborales, Riesgos,
                           Accidentes, SimpleExam, Examinacion, Consulta)
from docapp.forms import (OcupaForm,
                          ant_familiares_section,
                          ant_gineco_section,
                          revision_sistemas_section,
                          biometria_section,
                          habito_alcohol_section, habito_cigarillo_section, habito_droga_section,
                          habito_general_section,
                          examen_fisico_general_section, examen_fisico_abdomen_section, examen_fisico_boca_section,
                          examen_fisico_columna_section, examen_fisico_corazon_section, examen_fisico_cuello_section,
                          examen_fisico_extremidades_section, examen_fisico_genito_unitario_section,
                          examen_fisico_nariz_section, examen_fisico_neurologico_section, examen_fisico_oidos_section,
                          examen_fisico_ojos_section, examen_fisico_torax_pulmones_section,
                          conclusion_ingreso_section,
                          conclusion_periodico_section,
                          conclusion_post_incapacidad_section,
                          conclusion_retiro_section)

from docapp.forms import (AudioForm,
                          ananmesis_section,
                          ant_familiar_section,
                          ant_otro_section,
                          exposicion_audifonos_section, exposicion_moto_section, exposicion_auto_section,
                          exposicion_pesada_section,
                          estado_actual_ruido_molestia_section, estado_actual_volumen_tv_section,
                          estado_actual_frases_repetidas_section, estado_actual_escucha_section,
                          estado_actual_escucha_ruido_section,
                          audiometria_section)

from docapp.forms import (VisioForm, sintomas_section, ant_enfermedad_section, ant_uso_lentes_section,
                          ant_extra_exams, agudeza_section, cronomatica_section,
                          AntLaboralesForm, hazards_inlineformset, accident_inlineformset)

from docapp.forms import AlturaForm, question_section, SimpleExamForm

from docproject.helpers.chekers import CheckDoctor, CheckLaboratory, CheckUser
from docproject.helpers.customs import (FormViewPutExtra, FormsetPostManager, BaseRegisterExamBehavior,
                                        BaseExamUpdateBehavior)
from docapp.choices import ExamStates
from django.shortcuts import get_object_or_404

from accounts.models import DoctorProfile, ReceptionProfile


class RegisterOccupational(LoginRequiredMixin, CheckDoctor, BaseRegisterExamBehavior, FormsetPostManager,
                           FormViewPutExtra):
    model = Occupational
    form_class = OcupaForm
    template_name = 'docapp/register/exams/occupational.html'
    extra_context = {'exam_name': 'ocupacional',
                     'parent_object_key': 'ocupacional_id',
                     'child_name': 'ocupacional',
                     'formsets': [
                         {'section_name': 'ant_familiares',
                          'title': 'Antecedentes Familiares',
                          'form': ant_familiares_section},
                         None,
                         {'section_name': 'revision_sistemas',
                          'title': 'Revision por Sistemas',
                          'form': revision_sistemas_section},
                         # Habitos
                         {'section_name': 'habitos_generales',
                          'title': 'Habitos Generales',
                          'form': habito_general_section},
                         {'section_name': 'habito_alcohol',
                          'title': 'Habito Alcohol',
                          'form': habito_alcohol_section},
                         {'section_name': 'habito_cigarrillo',
                          'title': 'Habito Cigarillo',
                          'form': habito_cigarillo_section},
                         {'section_name': 'habito_droga',
                          'title': 'Habito Droga',
                          'form': habito_droga_section},
                         # Examen Fisico
                         {'section_name': 'aspecto_general',
                          'title': 'Aspecto General',
                          'form': examen_fisico_general_section},
                         {'section_name': 'biometria',
                          'title': 'Biometria',
                          'form': biometria_section},
                         # # Organos de los sentidos
                         {'section_name': 'org_boca',
                          'title': 'Boca',
                          'form': examen_fisico_boca_section},
                         {'section_name': 'org_nariz',
                          'title': 'Nariz',
                          'form': examen_fisico_nariz_section},
                         {'section_name': 'org_oidos',
                          'title': 'Oidos',
                          'form': examen_fisico_oidos_section},
                         {'section_name': 'org_ojos',
                          'title': 'Ojos',
                          'form': examen_fisico_ojos_section},
                         # # Fin Organos
                         {'section_name': 'exm_cuello',
                          'title': 'Cuello',
                          'form': examen_fisico_cuello_section},
                         {'section_name': 'exm_torax_pulmones',
                          'title': 'Torax y Pulmones',
                          'form': examen_fisico_torax_pulmones_section},
                         {'section_name': 'exm_corazon',
                          'title': 'Corazon',
                          'form': examen_fisico_corazon_section},
                         {'section_name': 'exm_abdomen',
                          'title': 'Abdomen',
                          'form': examen_fisico_abdomen_section},
                         {'section_name': 'exm_columna',
                          'title': 'Columna',
                          'form': examen_fisico_columna_section},
                         {'section_name': 'exm_extremidades',
                          'title': 'Extremidades',
                          'form': examen_fisico_extremidades_section},
                         {'section_name': 'exm_neurologico',
                          'title': 'Neurologico',
                          'form': examen_fisico_neurologico_section},
                         {'section_name': 'exm_genito_unitario',
                          'title': 'Genito Unitario',
                          'form': examen_fisico_genito_unitario_section},
                         # Fin examen fisico
                         None
                     ]
                     }

    def get_context_data(self, **kwargs):
        examination = self.get_object()
        examination_patient = examination.paciente_id
        if examination_patient.sexo == 'femenino' and self.extra_context['formsets'][1] is None:
            self.extra_context['formsets'][1] = {'section_name': 'ant_gineco',
                                                 'title': 'Antecedentes Gineco-Obstricos',
                                                 'form': ant_gineco_section}
        if self.extra_context['formsets'][21] is None:
            conclusion_section = {'section_name': 'conclusion',
                                  'title': 'Conclusion',
                                  'form': None}
            if examination.tipo == 'ingreso':
                conclusion_section.update({'form': conclusion_ingreso_section})
            elif examination.tipo == 'periodico':
                conclusion_section.update({'form': conclusion_periodico_section})
            elif examination.tipo == 'retiro' or examination.tipo == 'reubicacion':
                conclusion_section.update({'form': conclusion_retiro_section})
            elif examination.tipo == 'post-incapacidad':
                conclusion_section.update({'form': conclusion_post_incapacidad_section})
            else:
                raise SuspiciousOperation("Contact Admin")

            self.extra_context['formsets'][21] = conclusion_section
        return super(RegisterOccupational, self).get_context_data(**kwargs)


register_occupational = RegisterOccupational.as_view()


class UpdateOccupational(LoginRequiredMixin, CheckDoctor, BaseExamUpdateBehavior, FormsetPostManager, UpdateView):
    model = Occupational
    form_class = OcupaForm
    template_name = 'docapp/register/exams/occupational.html'
    extra_context = {'exam_name': 'ocupacional',
                     'parent_object_key': 'ocupacional_id',
                     'formsets': [
                         {'section_name': 'ant_familiares',
                          'title': 'Antecedentes Familiares',
                          'form': ant_familiares_section},
                         None,
                         {'section_name': 'revision_sistemas',
                          'title': 'Revision por Sistemas',
                          'form': revision_sistemas_section},

templates/docapp/details/alert_secure.html
<!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h3 class="modal-title" id="exampleModalLabel">Notificacion</h3>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <div class='col-12'>
                <h3 class='text-center' id='message_title'></h3>
                  <div class='text-center'>
                      <button class='btn btn-success' data-dismiss="modal"  id= "modal_process" >Si</button>
                      <button class='btn btn-danger' data-dismiss="modal">No</button>
                  </div>
            </div>
          </div>
          <div class="modal-footer">
          </div>
        </div>
      </div>
    </div>

<script>

</script>

templates/docapp/details/antecedent.html
<div class="panel-body">
    <!-- Title -->
    <div class="row">
        <div class="col-sm-12 text-center">
            {% if request.user.doctor_profile %}
                <span class="pull-right">
                                <a href="{% url 'docapp:update_employ_antecedent' antecedent_id=antecedent.id %}">
                                                <button class="btn btn-warning btn-xs" data-toggle="tooltip"
                                                        data-placement="left" title="" data-original-title="Editar">
                                                    <i class="fa fa-edit" aria-hidden="true"></i>
                                                </button>
                                            </a>
                            </span>
            {% endif %}
            <h1>Antecedentes de {{ antecedent.persona }}</h1>
            <small style="color: gainsboro">Registrado por: {{ antecedent.registrado_por.user_id.username }}</small>
        </div>
    </div>
    <hr>
    <!-- Information -->
    <div class="row">
        <div class="col-sm-12 text-left">
            <p><b>Empresa donde laboro:</b> {{ antecedent.nombre_empresa }}</p>
            <p><b>Cargo que tuvo:</b> {{ antecedent.ocupacion }}</p>
            <p><b>Tiempo de duracion:</b> {{ antecedent.tiempo }}</p>
            <p><b>Uso EPP:</b> {{ antecedent.uso_epp }}</p>
            <p><b>Numero de riesgos:</b> {{ antecedent.riesgos.get_number_hazard }}</p>
            <p><b>Riesgos:</b> {{ antecedent.riesgos.get_label_hazards }} </p>
            <p><b>Registrado por:</b> {{ antecedent.registrado_por.user_id.username }}</p>
            <p><b>Ultima vez modificado:</b> {{ antecedent.ultima_vez_modificado }}</p>
        </div>
    </div>
    <hr>
    <div class="row">
        <div class="col-sm-12">
            {% for accident in antecedent.accidentes.all %}
                <h4>Accidente #{{ forloop.counter }}</h4>
                <hr>
                <p><b>Tipo:</b> {{ accident.tipo }}</p>
                <p><b>Secuelas:</b> {{ accident.secuelas }}</p>
                <p><b>Atendido:</b> {{ accident.atendido }}</p>
                <p><b>Calificado:</b> {{ accident.calificado }}</p>
                <p><b>Fecha:</b> {{ accident.fecha }}</p>
                <p><b>Descripcion:</b> {{ accident.descripcion }}</p>
                <hr>
            {% empty %}
                <h2>No se registran accidentes</h2>
            {% endfor %}
        </div>
    </div>
</div>

templates/docapp/details/company.html
<div class="panel-body">
    <div class="row">
        <div class="col-sm-12 text-center">
            {% if request.user.reception_profile %}
                <span class="pull-right">
                            <a href="{% url 'docapp:update_company' company_id=company.id %}">
                                                <button class="btn btn-warning btn-xs" data-toggle="tooltip"
                                                        data-placement="left" title="" data-original-title="Editar">
                                                    <i class="fa fa-edit" aria-hidden="true"></i>
                                                </button>
                                            </a>
                            </span>
            {% endif %}
            <h1>{{ company.nombre|escape }}</h1>
            <address>
                <abbr title="NIT">{{ company.nit }}</abbr><br>
                <abbr title="Dirección">{{ company.direccion }}</abbr><br>
                <abbr title="Telefono"> {{ company.telefono }}</abbr><br>
                <abbr title="Celular">{{ company.celular }}</abbr><br>
                <a href="mailto:{{ company.correo_contacto }}">{{ company.correo_contacto }}</a>
            </address>
            <address>
                <p><b>Ultima vez modificado: </b> {{ company.ultima_vez_modificado }}</p>
            </address>
            <small style="color: gainsboro">Registrado por: {{ company.registrado_por.user }}</small>
        </div>
    </div>
    <hr>
    <h2>Empleados registrados</h2>
    <div class="table-responsive m-b-20">
        {% if company.empleados.all %}
            <table class="table table-striped">
                <thead>
                <tr>
                    <th>Identificacion</th>
                    <th>Nombre</th>
                    <th>Apellido</th>
                    <th>Telefono</th>
                    <th>Celular</th>
                    <th>Sexo</th>
                </tr>
                </thead>

                <tbody>
                {% for person in company.empleados.all %}
                    <tr>
                        <td>{{ person.identificacion }}</td>
                        <td>{{ person.nombres }}</td>
                        <td>{{ person.apellidos }}</td>
                        <td>{{ person.telefono }}</td>
                        <td>{{ person.celular }}</td>
                        <td>{{ person.sexo }}</td>
                    </tr>
                    {% if forloop.counter == 5 %}
                        {{ break }}
                    {% endif %}
                {% endfor %}
                </tbody>
            </table>
            <hr>
            <a class="btn btn-success pull-right"
               href="{% url 'docapp:list_employ_company' company_id=company.id %}"><i
                    class="fa fa-plus"></i>
                Ver más
            </a>
        {% else %}
            <h2>No se encuentran empleados registrados</h2>
        {% endif %}
    </div>
</div>

templates/docapp/details/examination.html
<div class="row">
    <div class="col-sm-12">
        <h2>Paciente: {{ exam.paciente_id }}</h2>
        <p><b>Proceso:</b> {{ exam.id }}</p>
        <p><b>Identificacion: </b>{{ exam.paciente_id.identificacion }}</p>
        <p><b>Tipo de examinacion:</b> {{ exam.tipo }} </p>
        {% if request.user.reception_profile %}
            <p><b>Doctor:</b> {% if exam.manejador_por %} {{ exam.manejador_por.user_id }} {% else %} No
                asignado {% endif %}</p>
            {% if exam.examenes_laboratorios.all %}
                {% with p_lab=exam.examenes_laboratorios.all.0 %}
                    <p><b>Laboratorio:</b> {{ p_lab.laboratorio_id }}</p>
                    <p><b>Personal de laboratorio:</b>
                        {% if p_lab.manejado_por %}{{ p_lab.manejado_por }}{% else %} No asignado {% endif %}</p>
                {% endwith %}
            {% else %}
                <p><b>No presenta examenes de laboratorio</b></p>
            {% endif %}
        {% endif %}
        <small><span class="label label-warning-outline">No registrado</span> <span
                class="label label-success-outline">Registrado</span></small>
    </div>
</div>
{% if request.user.doctor_profile %}
    <div class="row">
        <div class="col-sm-12"><h2>Porcentaje del proceso</h2></div>
        <div class="col-sm-12">
            <div class="progress progress-lg" style="max-width: none">
                <div {% if exam.get_doctor_process > 0 %}
                    class="progress-bar progress-bar-striped active progress-bar-success"
                    style="width: {{ exam.get_doctor_process }}%"
                {% else %}
                    class="progress-bar  progress-bar-striped active progress-bar-danger" style="width: 100%"
                {% endif %}
                    role="progressbar" aria-valuenow="{{ exam.get_doctor_process }}" aria-valuemin="0"
                    aria-valuemax="100">
                    {{ exam.get_doctor_process }}% Realizado
                </div>
            </div>
        </div>
    </div>
    {# Common Exams #}
    <div class="row">
        <div class="col-sm-12">
            <h3>Examenes comunes a realizar</h3>
            <ul>
                {% if exam.do_exam_altura %}
                    <li>
                        <span class="label {% if exam.altura %} label-success-outline {% else %} label-warning-outline {% endif %}">
                            <a href="{% url 'docapp:register_altura' exam_id=exam.id %}">Registrar Resultados Altura</a>
                        </span>
                    </li>
                {% endif %}
                {% if exam.do_exam_audiologia %}

                    <li>
                        <span class="label {% if exam.audiologia %} label-success-outline {% else %} label-warning-outline {% endif %}">
                            <a href="{% url 'docapp:register_audiology' exam_id=exam.id %}">Registrar Resultados Audiologia</a>
                        </span>
                    </li>
                {% endif %}
                {% if exam.do_exam_visiometria %}

                    <li>
                        <span class="label {% if exam.visiometria %} label-success-outline {% else %} label-warning-outline {% endif %}">
                            <a href="{% url 'docapp:register_visiometry' exam_id=exam.id %}">Registrar Resultados Visiometria</a>
                        </span>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
    {# Inter Exams #}
    <div class="row">
        <div class="col-sm-12">
            <h3>Examenes internos a realizar</h3>
            {% if exam.examenes_internos.all %}
                <ul>
                    {% for examen in exam.examenes_internos.all %}
                        <li class="m-t-20">
                        <span class="label {% if examen.resultados != '' %} label-success-outline {% else %} label-warning-outline {% endif %}">
                                <a href="{% url 'docapp:register_simple_exam' pk=examen.id %}">Registrar resultados
                                de {{ examen.nombre }}</a>
                        </span>
                        </li>
                    {% endfor %}
                </ul>
            {% endif %}
        </div>
    </div>
    {# Done process #}
    <div class="row">
        <div class="col-sm-12">
                <span class="pull-right">
                    <a href="{% url 'docapp:register_occupational' exam_id=exam.id %}">
                    <button class="btn btn-primary">Registrar Resumen del proceso <i
                            class="fa fa-drivers-license-o"></i></button></a>
                </span>
        </div>
    </div>
{% elif request.user.laboratory_profile %}
    <div class="row">
        <div class="col-sm-12"><h2>Porcentaje del proceso</h2></div>
        <div class="col-sm-12">
            <div class="progress progress-lg" style="max-width: none">
                <div {% if exam.get_lab_process > 0 %}
                    class="progress-bar progress-bar-striped active progress-bar-success"
                    style="width: {{ exam.get_lab_process }}%"
                {% else %}
                    class="progress-bar  progress-bar-striped active progress-bar-danger" style="width: 100%"
                {% endif %}
                    role="progressbar" aria-valuenow="80" aria-valuemin="0"
                    aria-valuemax="100">
                    {{ exam.get_lab_process }}% Realizado
                </div>
            </div>
        </div>
    </div>
    {# Examenes de laboratorio #}
    <div class="row">
        <div class="col-sm-12">
            <h3>Examenes de laboratorios a realizar</h3>
            {% if exam.examenes_laboratorios.all %}
                <ul>
                    {% for examen in exam.examenes_laboratorios.all %}
                        <li class="m-t-20">
                        <span class="label {% if examen.resultados.all %} label-success-outline {% else %} label-warning-outline {% endif %}">
                                <a href="{% url 'labapp:register_lab_exam_result' pk=examen.id %}">Registrar resultados
                                de {{ examen.nombre }}</a>
                        </span>
                        </li>
                    {% endfor %}
                </ul>
            {% endif %}
        </div>
    </div>
{% elif request.user.reception_profile %}
    <div class="row">
        <div class="col-sm-12"><h2>Porcentaje del proceso</h2></div>
        <div class="col-sm-12">
            <label for="doc_process">Doctor</label>
            <div class="progress progress-lg" id="doc_process" style="max-width: none">
                <div {% if exam.get_doctor_process > 0 %}
                    class="progress-bar progress-bar-striped active progress-bar-success"
                    style="width: {{ exam.get_doctor_process }}%"
                {% else %}
                    class="progress-bar  progress-bar-striped active progress-bar-danger" style="width: 100%"
                {% endif %}
                    role="progressbar" aria-valuenow="{{ exam.get_doctor_process }}" aria-valuemin="0"
                    aria-valuemax="100">
                    {{ exam.get_doctor_process }}% Realizado
                </div>
            </div>
        </div>
        <div class="col-sm-12">
            <label for="lab_process">Laboratorio</label>
            <div class="progress progress-lg" id="lab_process" style="max-width: none">
                <div {% if exam.get_lab_process > 0 %}
                    class="progress-bar progress-bar-striped active progress-bar-success"
                    style="width: {{ exam.get_lab_process }}%"
                {% else %}
                    class="progress-bar  progress-bar-striped active progress-bar-danger" style="width: 100%"
                {% endif %}
                    role="progressbar" aria-valuenow="80" aria-valuemin="0"
                    aria-valuemax="100">
                    {{ exam.get_lab_process }}% Realizado
                </div>
            </div>
        </div>
    </div>
{% endif %}